apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ncec2b0l4-python
  janus-idp.io/tekton: ncec2b0l4-python
  backstage.io/kubernetes-id: ncec2b0l4-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ncec2b0l4-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
